# Generated by Django 2.1.8 on 2019-05-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0002_barlike_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='first_menu',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='fourth_menu',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='second_menu',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='third_menu',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
