# Generated by Django 2.1.8 on 2019-05-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0003_auto_20190514_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bar',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='bar',
            name='first_menu',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bar',
            name='fourth_menu',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bar',
            name='second_menu',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bar',
            name='third_menu',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
