# Generated by Django 2.1.8 on 2019-05-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='delete',
        ),
        migrations.AddField(
            model_name='letter',
            name='delete_from',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='delete_to',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
