# Generated by Django 2.1.8 on 2019-05-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190515_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='check',
        ),
        migrations.AddField(
            model_name='letter',
            name='check_from',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='check_to',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
